# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca9ff993be4b9e03e0b48dbbf105e05d9b95a05d2512373100bd839c85f84961fbb3b29ef6add29204cb293258eb4996eca10ced34c3e862ac21c66bee0e07d5

test:
  secret_key_base: 9d2902865d513da9262d0ae6d0a64a79579123b2d471aeff4648a94c7dc2e10873c96c20daa15658267c4df063ade37c943490afb108e00c5349b08881c56fee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
